#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLQT")]
	public partial class QLQTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBacSis(BacSis instance);
    partial void UpdateBacSis(BacSis instance);
    partial void DeleteBacSis(BacSis instance);
    partial void InsertBenhNhans(BenhNhans instance);
    partial void UpdateBenhNhans(BenhNhans instance);
    partial void DeleteBenhNhans(BenhNhans instance);
    partial void InsertCTDonThuocs(CTDonThuocs instance);
    partial void UpdateCTDonThuocs(CTDonThuocs instance);
    partial void DeleteCTDonThuocs(CTDonThuocs instance);
    partial void InsertCTHoaDons(CTHoaDons instance);
    partial void UpdateCTHoaDons(CTHoaDons instance);
    partial void DeleteCTHoaDons(CTHoaDons instance);
    partial void InsertHoaDons(HoaDons instance);
    partial void UpdateHoaDons(HoaDons instance);
    partial void DeleteHoaDons(HoaDons instance);
    partial void InsertLoaiThuocs(LoaiThuocs instance);
    partial void UpdateLoaiThuocs(LoaiThuocs instance);
    partial void DeleteLoaiThuocs(LoaiThuocs instance);
    partial void InsertNCCs(NCCs instance);
    partial void UpdateNCCs(NCCs instance);
    partial void DeleteNCCs(NCCs instance);
    partial void InsertNhanViens(NhanViens instance);
    partial void UpdateNhanViens(NhanViens instance);
    partial void DeleteNhanViens(NhanViens instance);
    partial void InsertNVBanThuocs(NVBanThuocs instance);
    partial void UpdateNVBanThuocs(NVBanThuocs instance);
    partial void DeleteNVBanThuocs(NVBanThuocs instance);
    partial void InsertNVThongKes(NVThongKes instance);
    partial void UpdateNVThongKes(NVThongKes instance);
    partial void DeleteNVThongKes(NVThongKes instance);
    partial void InsertQuanLys(QuanLys instance);
    partial void UpdateQuanLys(QuanLys instance);
    partial void DeleteQuanLys(QuanLys instance);
    partial void InsertTaiKhoans(TaiKhoans instance);
    partial void UpdateTaiKhoans(TaiKhoans instance);
    partial void DeleteTaiKhoans(TaiKhoans instance);
    partial void InsertThuocs(Thuocs instance);
    partial void UpdateThuocs(Thuocs instance);
    partial void DeleteThuocs(Thuocs instance);
    partial void InsertDonThuocs(DonThuocs instance);
    partial void UpdateDonThuocs(DonThuocs instance);
    partial void DeleteDonThuocs(DonThuocs instance);
    partial void InsertLoThuocs(LoThuocs instance);
    partial void UpdateLoThuocs(LoThuocs instance);
    partial void DeleteLoThuocs(LoThuocs instance);
    #endregion
		
		public QLQTDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLQTConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLQTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BacSis> BacSis
		{
			get
			{
				return this.GetTable<BacSis>();
			}
		}
		
		public System.Data.Linq.Table<BenhNhans> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhans>();
			}
		}
		
		public System.Data.Linq.Table<CTDonThuocs> CTDonThuocs
		{
			get
			{
				return this.GetTable<CTDonThuocs>();
			}
		}
		
		public System.Data.Linq.Table<CTHoaDons> CTHoaDons
		{
			get
			{
				return this.GetTable<CTHoaDons>();
			}
		}
		
		public System.Data.Linq.Table<HoaDons> HoaDons
		{
			get
			{
				return this.GetTable<HoaDons>();
			}
		}
		
		public System.Data.Linq.Table<LoaiThuocs> LoaiThuocs
		{
			get
			{
				return this.GetTable<LoaiThuocs>();
			}
		}
		
		public System.Data.Linq.Table<NCCs> NCCs
		{
			get
			{
				return this.GetTable<NCCs>();
			}
		}
		
		public System.Data.Linq.Table<NhanViens> NhanViens
		{
			get
			{
				return this.GetTable<NhanViens>();
			}
		}
		
		public System.Data.Linq.Table<NVBanThuocs> NVBanThuocs
		{
			get
			{
				return this.GetTable<NVBanThuocs>();
			}
		}
		
		public System.Data.Linq.Table<NVThongKes> NVThongKes
		{
			get
			{
				return this.GetTable<NVThongKes>();
			}
		}
		
		public System.Data.Linq.Table<QuanLys> QuanLys
		{
			get
			{
				return this.GetTable<QuanLys>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoans> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoans>();
			}
		}
		
		public System.Data.Linq.Table<Thuocs> Thuocs
		{
			get
			{
				return this.GetTable<Thuocs>();
			}
		}
		
		public System.Data.Linq.Table<DonThuocs> DonThuocs
		{
			get
			{
				return this.GetTable<DonThuocs>();
			}
		}
		
		public System.Data.Linq.Table<LoThuocs> LoThuocs
		{
			get
			{
				return this.GetTable<LoThuocs>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BacSi")]
	public partial class BacSis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBacSi;
		
		private string _TenBacSi;
		
		private string _Khoa;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private EntitySet<TaiKhoans> _TaiKhoans;
		
		private EntitySet<DonThuocs> _DonThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBacSiChanging(string value);
    partial void OnMaBacSiChanged();
    partial void OnTenBacSiChanging(string value);
    partial void OnTenBacSiChanged();
    partial void OnKhoaChanging(string value);
    partial void OnKhoaChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public BacSis()
		{
			this._TaiKhoans = new EntitySet<TaiKhoans>(new Action<TaiKhoans>(this.attach_TaiKhoans), new Action<TaiKhoans>(this.detach_TaiKhoans));
			this._DonThuocs = new EntitySet<DonThuocs>(new Action<DonThuocs>(this.attach_DonThuocs), new Action<DonThuocs>(this.detach_DonThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBacSi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBacSi
		{
			get
			{
				return this._MaBacSi;
			}
			set
			{
				if ((this._MaBacSi != value))
				{
					this.OnMaBacSiChanging(value);
					this.SendPropertyChanging();
					this._MaBacSi = value;
					this.SendPropertyChanged("MaBacSi");
					this.OnMaBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBacSi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenBacSi
		{
			get
			{
				return this._TenBacSi;
			}
			set
			{
				if ((this._TenBacSi != value))
				{
					this.OnTenBacSiChanging(value);
					this.SendPropertyChanging();
					this._TenBacSi = value;
					this.SendPropertyChanged("TenBacSi");
					this.OnTenBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Khoa
		{
			get
			{
				return this._Khoa;
			}
			set
			{
				if ((this._Khoa != value))
				{
					this.OnKhoaChanging(value);
					this.SendPropertyChanging();
					this._Khoa = value;
					this.SendPropertyChanged("Khoa");
					this.OnKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSis_TaiKhoans", Storage="_TaiKhoans", ThisKey="MaBacSi", OtherKey="MaBacSi")]
		public EntitySet<TaiKhoans> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSis_DonThuocs", Storage="_DonThuocs", ThisKey="MaBacSi", OtherKey="MaBacSi")]
		public EntitySet<DonThuocs> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoans entity)
		{
			this.SendPropertyChanging();
			entity.BacSis = this;
		}
		
		private void detach_TaiKhoans(TaiKhoans entity)
		{
			this.SendPropertyChanging();
			entity.BacSis = null;
		}
		
		private void attach_DonThuocs(DonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.BacSis = this;
		}
		
		private void detach_DonThuocs(DonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.BacSis = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhans : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBenhNhan;
		
		private string _TenBenhNhan;
		
		private int _NamSinh;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private EntitySet<HoaDons> _HoaDons;
		
		private EntitySet<DonThuocs> _DonThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnTenBenhNhanChanging(string value);
    partial void OnTenBenhNhanChanged();
    partial void OnNamSinhChanging(int value);
    partial void OnNamSinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public BenhNhans()
		{
			this._HoaDons = new EntitySet<HoaDons>(new Action<HoaDons>(this.attach_HoaDons), new Action<HoaDons>(this.detach_HoaDons));
			this._DonThuocs = new EntitySet<DonThuocs>(new Action<DonThuocs>(this.attach_DonThuocs), new Action<DonThuocs>(this.detach_DonThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenhNhan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenBenhNhan
		{
			get
			{
				return this._TenBenhNhan;
			}
			set
			{
				if ((this._TenBenhNhan != value))
				{
					this.OnTenBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._TenBenhNhan = value;
					this.SendPropertyChanged("TenBenhNhan");
					this.OnTenBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Int NOT NULL")]
		public int NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhans_HoaDons", Storage="_HoaDons", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan")]
		public EntitySet<HoaDons> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhans_DonThuocs", Storage="_DonThuocs", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan")]
		public EntitySet<DonThuocs> DonThuocs
		{
			get
			{
				return this._DonThuocs;
			}
			set
			{
				this._DonThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDons entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhans = this;
		}
		
		private void detach_HoaDons(HoaDons entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhans = null;
		}
		
		private void attach_DonThuocs(DonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhans = this;
		}
		
		private void detach_DonThuocs(DonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhans = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTDonThuoc")]
	public partial class CTDonThuocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonThuoc;
		
		private string _MaThuoc;
		
		private int _SoLuong;
		
		private string _DVT;
		
		private string _GhiChu;
		
		private EntityRef<Thuocs> _Thuocs;
		
		private EntityRef<DonThuocs> _DonThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonThuocChanging(string value);
    partial void OnMaDonThuocChanged();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public CTDonThuocs()
		{
			this._Thuocs = default(EntityRef<Thuocs>);
			this._DonThuocs = default(EntityRef<DonThuocs>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonThuoc
		{
			get
			{
				return this._MaDonThuoc;
			}
			set
			{
				if ((this._MaDonThuoc != value))
				{
					if (this._DonThuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonThuocChanging(value);
					this.SendPropertyChanging();
					this._MaDonThuoc = value;
					this.SendPropertyChanged("MaDonThuoc");
					this.OnMaDonThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					if (this._Thuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(100)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuocs_CTDonThuocs", Storage="_Thuocs", ThisKey="MaThuoc", OtherKey="MaThuoc", IsForeignKey=true)]
		public Thuocs Thuocs
		{
			get
			{
				return this._Thuocs.Entity;
			}
			set
			{
				Thuocs previousValue = this._Thuocs.Entity;
				if (((previousValue != value) 
							|| (this._Thuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuocs.Entity = null;
						previousValue.CTDonThuocs.Remove(this);
					}
					this._Thuocs.Entity = value;
					if ((value != null))
					{
						value.CTDonThuocs.Add(this);
						this._MaThuoc = value.MaThuoc;
					}
					else
					{
						this._MaThuoc = default(string);
					}
					this.SendPropertyChanged("Thuocs");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonThuocs_CTDonThuocs", Storage="_DonThuocs", ThisKey="MaDonThuoc", OtherKey="MaDonThuoc", IsForeignKey=true)]
		public DonThuocs DonThuocs
		{
			get
			{
				return this._DonThuocs.Entity;
			}
			set
			{
				DonThuocs previousValue = this._DonThuocs.Entity;
				if (((previousValue != value) 
							|| (this._DonThuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonThuocs.Entity = null;
						previousValue.CTDonThuocs.Remove(this);
					}
					this._DonThuocs.Entity = value;
					if ((value != null))
					{
						value.CTDonThuocs.Add(this);
						this._MaDonThuoc = value.MaDonThuoc;
					}
					else
					{
						this._MaDonThuoc = default(string);
					}
					this.SendPropertyChanged("DonThuocs");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHoaDon")]
	public partial class CTHoaDons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaLoThuoc;
		
		private string _DVT;
		
		private int _SoLuong;
		
		private decimal _GiaBan;
		
		private EntityRef<HoaDons> _HoaDons;
		
		private EntityRef<LoThuocs> _LoThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaLoThuocChanging(string value);
    partial void OnMaLoThuocChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnGiaBanChanging(decimal value);
    partial void OnGiaBanChanged();
    #endregion
		
		public CTHoaDons()
		{
			this._HoaDons = default(EntityRef<HoaDons>);
			this._LoThuocs = default(EntityRef<LoThuocs>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					if (this._HoaDons.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoThuoc
		{
			get
			{
				return this._MaLoThuoc;
			}
			set
			{
				if ((this._MaLoThuoc != value))
				{
					if (this._LoThuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoThuocChanging(value);
					this.SendPropertyChanging();
					this._MaLoThuoc = value;
					this.SendPropertyChanged("MaLoThuoc");
					this.OnMaLoThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Money NOT NULL")]
		public decimal GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDons_CTHoaDons", Storage="_HoaDons", ThisKey="MaHoaDon", OtherKey="MaHoaDon", IsForeignKey=true)]
		public HoaDons HoaDons
		{
			get
			{
				return this._HoaDons.Entity;
			}
			set
			{
				HoaDons previousValue = this._HoaDons.Entity;
				if (((previousValue != value) 
							|| (this._HoaDons.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDons.Entity = null;
						previousValue.CTHoaDons.Remove(this);
					}
					this._HoaDons.Entity = value;
					if ((value != null))
					{
						value.CTHoaDons.Add(this);
						this._MaHoaDon = value.MaHoaDon;
					}
					else
					{
						this._MaHoaDon = default(string);
					}
					this.SendPropertyChanged("HoaDons");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoThuoc_CTHoaDons", Storage="_LoThuocs", ThisKey="MaLoThuoc", OtherKey="MaLoThuoc", IsForeignKey=true)]
		public LoThuocs LoThuocs
		{
			get
			{
				return this._LoThuocs.Entity;
			}
			set
			{
				LoThuocs previousValue = this._LoThuocs.Entity;
				if (((previousValue != value) 
							|| (this._LoThuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoThuocs.Entity = null;
						previousValue.CTHoaDons.Remove(this);
					}
					this._LoThuocs.Entity = value;
					if ((value != null))
					{
						value.CTHoaDons.Add(this);
						this._MaLoThuoc = value.MaLoThuoc;
					}
					else
					{
						this._MaLoThuoc = default(string);
					}
					this.SendPropertyChanged("LoThuocs");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDons : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHoaDon;
		
		private string _MaNhanVien;
		
		private string _MaDonThuoc;
		
		private string _MaBenhNhan;
		
		private decimal _TongTien;
		
		private System.DateTime _NgayLapHD;
		
		private EntitySet<CTHoaDons> _CTHoaDons;
		
		private EntityRef<BenhNhans> _BenhNhans;
		
		private EntityRef<NVBanThuocs> _NVBanThuocs;
		
		private EntityRef<DonThuocs> _DonThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHoaDonChanging(string value);
    partial void OnMaHoaDonChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnMaDonThuocChanging(string value);
    partial void OnMaDonThuocChanged();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnTongTienChanging(decimal value);
    partial void OnTongTienChanged();
    partial void OnNgayLapHDChanging(System.DateTime value);
    partial void OnNgayLapHDChanged();
    #endregion
		
		public HoaDons()
		{
			this._CTHoaDons = new EntitySet<CTHoaDons>(new Action<CTHoaDons>(this.attach_CTHoaDons), new Action<CTHoaDons>(this.detach_CTHoaDons));
			this._BenhNhans = default(EntityRef<BenhNhans>);
			this._NVBanThuocs = default(EntityRef<NVBanThuocs>);
			this._DonThuocs = default(EntityRef<DonThuocs>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHoaDon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHoaDon
		{
			get
			{
				return this._MaHoaDon;
			}
			set
			{
				if ((this._MaHoaDon != value))
				{
					this.OnMaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._MaHoaDon = value;
					this.SendPropertyChanged("MaHoaDon");
					this.OnMaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NVBanThuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonThuoc", DbType="VarChar(10)")]
		public string MaDonThuoc
		{
			get
			{
				return this._MaDonThuoc;
			}
			set
			{
				if ((this._MaDonThuoc != value))
				{
					if (this._DonThuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonThuocChanging(value);
					this.SendPropertyChanging();
					this._MaDonThuoc = value;
					this.SendPropertyChanged("MaDonThuoc");
					this.OnMaDonThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10)")]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					if (this._BenhNhans.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money NOT NULL")]
		public decimal TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapHD", DbType="Date NOT NULL")]
		public System.DateTime NgayLapHD
		{
			get
			{
				return this._NgayLapHD;
			}
			set
			{
				if ((this._NgayLapHD != value))
				{
					this.OnNgayLapHDChanging(value);
					this.SendPropertyChanging();
					this._NgayLapHD = value;
					this.SendPropertyChanged("NgayLapHD");
					this.OnNgayLapHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDons_CTHoaDons", Storage="_CTHoaDons", ThisKey="MaHoaDon", OtherKey="MaHoaDon")]
		public EntitySet<CTHoaDons> CTHoaDons
		{
			get
			{
				return this._CTHoaDons;
			}
			set
			{
				this._CTHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhans_HoaDons", Storage="_BenhNhans", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan", IsForeignKey=true)]
		public BenhNhans BenhNhans
		{
			get
			{
				return this._BenhNhans.Entity;
			}
			set
			{
				BenhNhans previousValue = this._BenhNhans.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhans.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhans.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._BenhNhans.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaBenhNhan = value.MaBenhNhan;
					}
					else
					{
						this._MaBenhNhan = default(string);
					}
					this.SendPropertyChanged("BenhNhans");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NVBanThuocs_HoaDons", Storage="_NVBanThuocs", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NVBanThuocs NVBanThuocs
		{
			get
			{
				return this._NVBanThuocs.Entity;
			}
			set
			{
				NVBanThuocs previousValue = this._NVBanThuocs.Entity;
				if (((previousValue != value) 
							|| (this._NVBanThuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NVBanThuocs.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NVBanThuocs.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NVBanThuocs");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonThuocs_HoaDons", Storage="_DonThuocs", ThisKey="MaDonThuoc", OtherKey="MaDonThuoc", IsForeignKey=true)]
		public DonThuocs DonThuocs
		{
			get
			{
				return this._DonThuocs.Entity;
			}
			set
			{
				DonThuocs previousValue = this._DonThuocs.Entity;
				if (((previousValue != value) 
							|| (this._DonThuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonThuocs.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._DonThuocs.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaDonThuoc = value.MaDonThuoc;
					}
					else
					{
						this._MaDonThuoc = default(string);
					}
					this.SendPropertyChanged("DonThuocs");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDons(CTHoaDons entity)
		{
			this.SendPropertyChanging();
			entity.HoaDons = this;
		}
		
		private void detach_CTHoaDons(CTHoaDons entity)
		{
			this.SendPropertyChanging();
			entity.HoaDons = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiThuoc")]
	public partial class LoaiThuocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiThuoc;
		
		private string _TenLoaiThuoc;
		
		private EntitySet<Thuocs> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiThuocChanging(string value);
    partial void OnMaLoaiThuocChanged();
    partial void OnTenLoaiThuocChanging(string value);
    partial void OnTenLoaiThuocChanged();
    #endregion
		
		public LoaiThuocs()
		{
			this._Thuocs = new EntitySet<Thuocs>(new Action<Thuocs>(this.attach_Thuocs), new Action<Thuocs>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiThuoc
		{
			get
			{
				return this._MaLoaiThuoc;
			}
			set
			{
				if ((this._MaLoaiThuoc != value))
				{
					this.OnMaLoaiThuocChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThuoc = value;
					this.SendPropertyChanged("MaLoaiThuoc");
					this.OnMaLoaiThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiThuoc", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenLoaiThuoc
		{
			get
			{
				return this._TenLoaiThuoc;
			}
			set
			{
				if ((this._TenLoaiThuoc != value))
				{
					this.OnTenLoaiThuocChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiThuoc = value;
					this.SendPropertyChanged("TenLoaiThuoc");
					this.OnTenLoaiThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThuocs_Thuocs", Storage="_Thuocs", ThisKey="MaLoaiThuoc", OtherKey="MaLoaiThuoc")]
		public EntitySet<Thuocs> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuocs entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThuocs = this;
		}
		
		private void detach_Thuocs(Thuocs entity)
		{
			this.SendPropertyChanging();
			entity.LoaiThuocs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NCC")]
	public partial class NCCs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private EntitySet<LoThuocs> _LoThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    #endregion
		
		public NCCs()
		{
			this._LoThuocs = new EntitySet<LoThuocs>(new Action<LoThuocs>(this.attach_LoThuocs), new Action<LoThuocs>(this.detach_LoThuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NCCs_LoThuoc", Storage="_LoThuocs", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<LoThuocs> LoThuocs
		{
			get
			{
				return this._LoThuocs;
			}
			set
			{
				this._LoThuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LoThuocs(LoThuocs entity)
		{
			this.SendPropertyChanging();
			entity.NCCs = this;
		}
		
		private void detach_LoThuocs(LoThuocs entity)
		{
			this.SendPropertyChanging();
			entity.NCCs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanViens : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _GioiTinh;
		
		private string _SDT;
		
		private string _DiaChi;
		
		private string _Email;
		
		private int _TinhTrang;
		
		private EntityRef<NVBanThuocs> _NVBanThuocs;
		
		private EntityRef<NVThongKes> _NVThongKes;
		
		private EntitySet<TaiKhoans> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTinhTrangChanging(int value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public NhanViens()
		{
			this._NVBanThuocs = default(EntityRef<NVBanThuocs>);
			this._NVThongKes = default(EntityRef<NVThongKes>);
			this._TaiKhoans = new EntitySet<TaiKhoans>(new Action<TaiKhoans>(this.attach_TaiKhoans), new Action<TaiKhoans>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Int NOT NULL")]
		public int TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanViens_NVBanThuocs", Storage="_NVBanThuocs", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsUnique=true, IsForeignKey=false)]
		public NVBanThuocs NVBanThuocs
		{
			get
			{
				return this._NVBanThuocs.Entity;
			}
			set
			{
				NVBanThuocs previousValue = this._NVBanThuocs.Entity;
				if (((previousValue != value) 
							|| (this._NVBanThuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NVBanThuocs.Entity = null;
						previousValue.NhanViens = null;
					}
					this._NVBanThuocs.Entity = value;
					if ((value != null))
					{
						value.NhanViens = this;
					}
					this.SendPropertyChanged("NVBanThuocs");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanViens_NVThongKes", Storage="_NVThongKes", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsUnique=true, IsForeignKey=false)]
		public NVThongKes NVThongKes
		{
			get
			{
				return this._NVThongKes.Entity;
			}
			set
			{
				NVThongKes previousValue = this._NVThongKes.Entity;
				if (((previousValue != value) 
							|| (this._NVThongKes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NVThongKes.Entity = null;
						previousValue.NhanViens = null;
					}
					this._NVThongKes.Entity = value;
					if ((value != null))
					{
						value.NhanViens = this;
					}
					this.SendPropertyChanged("NVThongKes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanViens_TaiKhoans", Storage="_TaiKhoans", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<TaiKhoans> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoans entity)
		{
			this.SendPropertyChanging();
			entity.NhanViens = this;
		}
		
		private void detach_TaiKhoans(TaiKhoans entity)
		{
			this.SendPropertyChanging();
			entity.NhanViens = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NVBanThuoc")]
	public partial class NVBanThuocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private System.DateTime _NgayLamViec;
		
		private string _CaLamViec;
		
		private EntitySet<HoaDons> _HoaDons;
		
		private EntityRef<NhanViens> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnNgayLamViecChanging(System.DateTime value);
    partial void OnNgayLamViecChanged();
    partial void OnCaLamViecChanging(string value);
    partial void OnCaLamViecChanged();
    #endregion
		
		public NVBanThuocs()
		{
			this._HoaDons = new EntitySet<HoaDons>(new Action<HoaDons>(this.attach_HoaDons), new Action<HoaDons>(this.detach_HoaDons));
			this._NhanViens = default(EntityRef<NhanViens>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanViens.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamViec", DbType="Date NOT NULL")]
		public System.DateTime NgayLamViec
		{
			get
			{
				return this._NgayLamViec;
			}
			set
			{
				if ((this._NgayLamViec != value))
				{
					this.OnNgayLamViecChanging(value);
					this.SendPropertyChanging();
					this._NgayLamViec = value;
					this.SendPropertyChanged("NgayLamViec");
					this.OnNgayLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaLamViec", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CaLamViec
		{
			get
			{
				return this._CaLamViec;
			}
			set
			{
				if ((this._CaLamViec != value))
				{
					this.OnCaLamViecChanging(value);
					this.SendPropertyChanging();
					this._CaLamViec = value;
					this.SendPropertyChanged("CaLamViec");
					this.OnCaLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NVBanThuocs_HoaDons", Storage="_HoaDons", ThisKey="MaNhanVien", OtherKey="MaNhanVien")]
		public EntitySet<HoaDons> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanViens_NVBanThuocs", Storage="_NhanViens", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanViens NhanViens
		{
			get
			{
				return this._NhanViens.Entity;
			}
			set
			{
				NhanViens previousValue = this._NhanViens.Entity;
				if (((previousValue != value) 
							|| (this._NhanViens.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanViens.Entity = null;
						previousValue.NVBanThuocs = null;
					}
					this._NhanViens.Entity = value;
					if ((value != null))
					{
						value.NVBanThuocs = this;
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanViens");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDons entity)
		{
			this.SendPropertyChanging();
			entity.NVBanThuocs = this;
		}
		
		private void detach_HoaDons(HoaDons entity)
		{
			this.SendPropertyChanging();
			entity.NVBanThuocs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NVThongKe")]
	public partial class NVThongKes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private System.DateTime _NgayLamViec;
		
		private EntityRef<NhanViens> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnNgayLamViecChanging(System.DateTime value);
    partial void OnNgayLamViecChanged();
    #endregion
		
		public NVThongKes()
		{
			this._NhanViens = default(EntityRef<NhanViens>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanViens.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLamViec", DbType="Date NOT NULL")]
		public System.DateTime NgayLamViec
		{
			get
			{
				return this._NgayLamViec;
			}
			set
			{
				if ((this._NgayLamViec != value))
				{
					this.OnNgayLamViecChanging(value);
					this.SendPropertyChanging();
					this._NgayLamViec = value;
					this.SendPropertyChanged("NgayLamViec");
					this.OnNgayLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanViens_NVThongKes", Storage="_NhanViens", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanViens NhanViens
		{
			get
			{
				return this._NhanViens.Entity;
			}
			set
			{
				NhanViens previousValue = this._NhanViens.Entity;
				if (((previousValue != value) 
							|| (this._NhanViens.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanViens.Entity = null;
						previousValue.NVThongKes = null;
					}
					this._NhanViens.Entity = value;
					if ((value != null))
					{
						value.NVThongKes = this;
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanViens");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLy")]
	public partial class QuanLys : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNQL;
		
		private string _TenNQL;
		
		private EntitySet<TaiKhoans> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNQLChanging(string value);
    partial void OnMaNQLChanged();
    partial void OnTenNQLChanging(string value);
    partial void OnTenNQLChanged();
    #endregion
		
		public QuanLys()
		{
			this._TaiKhoans = new EntitySet<TaiKhoans>(new Action<TaiKhoans>(this.attach_TaiKhoans), new Action<TaiKhoans>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNQL", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNQL
		{
			get
			{
				return this._MaNQL;
			}
			set
			{
				if ((this._MaNQL != value))
				{
					this.OnMaNQLChanging(value);
					this.SendPropertyChanging();
					this._MaNQL = value;
					this.SendPropertyChanged("MaNQL");
					this.OnMaNQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNQL", DbType="VarChar(30)")]
		public string TenNQL
		{
			get
			{
				return this._TenNQL;
			}
			set
			{
				if ((this._TenNQL != value))
				{
					this.OnTenNQLChanging(value);
					this.SendPropertyChanging();
					this._TenNQL = value;
					this.SendPropertyChanged("TenNQL");
					this.OnTenNQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLys_TaiKhoans", Storage="_TaiKhoans", ThisKey="MaNQL", OtherKey="MaNQL")]
		public EntitySet<TaiKhoans> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TaiKhoans(TaiKhoans entity)
		{
			this.SendPropertyChanging();
			entity.QuanLys = this;
		}
		
		private void detach_TaiKhoans(TaiKhoans entity)
		{
			this.SendPropertyChanging();
			entity.QuanLys = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoans : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Pass;
		
		private string _LoaiTK;
		
		private string _MaNhanVien;
		
		private string _MaBacSi;
		
		private string _MaNQL;
		
		private EntityRef<BacSis> _BacSis;
		
		private EntityRef<NhanViens> _NhanViens;
		
		private EntityRef<QuanLys> _QuanLys;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassChanging(string value);
    partial void OnPassChanged();
    partial void OnLoaiTKChanging(string value);
    partial void OnLoaiTKChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnMaBacSiChanging(string value);
    partial void OnMaBacSiChanged();
    partial void OnMaNQLChanging(string value);
    partial void OnMaNQLChanged();
    #endregion
		
		public TaiKhoans()
		{
			this._BacSis = default(EntityRef<BacSis>);
			this._NhanViens = default(EntityRef<NhanViens>);
			this._QuanLys = default(EntityRef<QuanLys>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(16) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass", DbType="VarChar(16)")]
		public string Pass
		{
			get
			{
				return this._Pass;
			}
			set
			{
				if ((this._Pass != value))
				{
					this.OnPassChanging(value);
					this.SendPropertyChanging();
					this._Pass = value;
					this.SendPropertyChanged("Pass");
					this.OnPassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTK", DbType="VarChar(2)")]
		public string LoaiTK
		{
			get
			{
				return this._LoaiTK;
			}
			set
			{
				if ((this._LoaiTK != value))
				{
					this.OnLoaiTKChanging(value);
					this.SendPropertyChanging();
					this._LoaiTK = value;
					this.SendPropertyChanged("LoaiTK");
					this.OnLoaiTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(10)")]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					if (this._NhanViens.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBacSi", DbType="VarChar(10)")]
		public string MaBacSi
		{
			get
			{
				return this._MaBacSi;
			}
			set
			{
				if ((this._MaBacSi != value))
				{
					if (this._BacSis.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBacSiChanging(value);
					this.SendPropertyChanging();
					this._MaBacSi = value;
					this.SendPropertyChanged("MaBacSi");
					this.OnMaBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNQL", DbType="VarChar(10)")]
		public string MaNQL
		{
			get
			{
				return this._MaNQL;
			}
			set
			{
				if ((this._MaNQL != value))
				{
					if (this._QuanLys.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNQLChanging(value);
					this.SendPropertyChanging();
					this._MaNQL = value;
					this.SendPropertyChanged("MaNQL");
					this.OnMaNQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSis_TaiKhoans", Storage="_BacSis", ThisKey="MaBacSi", OtherKey="MaBacSi", IsForeignKey=true)]
		public BacSis BacSis
		{
			get
			{
				return this._BacSis.Entity;
			}
			set
			{
				BacSis previousValue = this._BacSis.Entity;
				if (((previousValue != value) 
							|| (this._BacSis.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BacSis.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._BacSis.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaBacSi = value.MaBacSi;
					}
					else
					{
						this._MaBacSi = default(string);
					}
					this.SendPropertyChanged("BacSis");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanViens_TaiKhoans", Storage="_NhanViens", ThisKey="MaNhanVien", OtherKey="MaNhanVien", IsForeignKey=true)]
		public NhanViens NhanViens
		{
			get
			{
				return this._NhanViens.Entity;
			}
			set
			{
				NhanViens previousValue = this._NhanViens.Entity;
				if (((previousValue != value) 
							|| (this._NhanViens.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanViens.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanViens.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaNhanVien = value.MaNhanVien;
					}
					else
					{
						this._MaNhanVien = default(string);
					}
					this.SendPropertyChanged("NhanViens");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLys_TaiKhoans", Storage="_QuanLys", ThisKey="MaNQL", OtherKey="MaNQL", IsForeignKey=true)]
		public QuanLys QuanLys
		{
			get
			{
				return this._QuanLys.Entity;
			}
			set
			{
				QuanLys previousValue = this._QuanLys.Entity;
				if (((previousValue != value) 
							|| (this._QuanLys.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanLys.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._QuanLys.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._MaNQL = value.MaNQL;
					}
					else
					{
						this._MaNQL = default(string);
					}
					this.SendPropertyChanged("QuanLys");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThuoc;
		
		private string _MaLoaiThuoc;
		
		private string _TenThuoc;
		
		private string _MoTa;
		
		private int _TrangThai;
		
		private EntitySet<CTDonThuocs> _CTDonThuocs;
		
		private EntitySet<LoThuocs> _LoThuocs;
		
		private EntityRef<LoaiThuocs> _LoaiThuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnMaLoaiThuocChanging(string value);
    partial void OnMaLoaiThuocChanged();
    partial void OnTenThuocChanging(string value);
    partial void OnTenThuocChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public Thuocs()
		{
			this._CTDonThuocs = new EntitySet<CTDonThuocs>(new Action<CTDonThuocs>(this.attach_CTDonThuocs), new Action<CTDonThuocs>(this.detach_CTDonThuocs));
			this._LoThuocs = new EntitySet<LoThuocs>(new Action<LoThuocs>(this.attach_LoThuocs), new Action<LoThuocs>(this.detach_LoThuocs));
			this._LoaiThuocs = default(EntityRef<LoaiThuocs>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiThuoc", DbType="VarChar(10)")]
		public string MaLoaiThuoc
		{
			get
			{
				return this._MaLoaiThuoc;
			}
			set
			{
				if ((this._MaLoaiThuoc != value))
				{
					if (this._LoaiThuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiThuocChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiThuoc = value;
					this.SendPropertyChanged("MaLoaiThuoc");
					this.OnMaLoaiThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this.OnTenThuocChanging(value);
					this.SendPropertyChanging();
					this._TenThuoc = value;
					this.SendPropertyChanged("TenThuoc");
					this.OnTenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(50)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuocs_CTDonThuocs", Storage="_CTDonThuocs", ThisKey="MaThuoc", OtherKey="MaThuoc")]
		public EntitySet<CTDonThuocs> CTDonThuocs
		{
			get
			{
				return this._CTDonThuocs;
			}
			set
			{
				this._CTDonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuocs_LoThuoc", Storage="_LoThuocs", ThisKey="MaThuoc", OtherKey="MaThuoc")]
		public EntitySet<LoThuocs> LoThuocs
		{
			get
			{
				return this._LoThuocs;
			}
			set
			{
				this._LoThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiThuocs_Thuocs", Storage="_LoaiThuocs", ThisKey="MaLoaiThuoc", OtherKey="MaLoaiThuoc", IsForeignKey=true)]
		public LoaiThuocs LoaiThuocs
		{
			get
			{
				return this._LoaiThuocs.Entity;
			}
			set
			{
				LoaiThuocs previousValue = this._LoaiThuocs.Entity;
				if (((previousValue != value) 
							|| (this._LoaiThuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiThuocs.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._LoaiThuocs.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._MaLoaiThuoc = value.MaLoaiThuoc;
					}
					else
					{
						this._MaLoaiThuoc = default(string);
					}
					this.SendPropertyChanged("LoaiThuocs");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTDonThuocs(CTDonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.Thuocs = this;
		}
		
		private void detach_CTDonThuocs(CTDonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.Thuocs = null;
		}
		
		private void attach_LoThuocs(LoThuocs entity)
		{
			this.SendPropertyChanging();
			entity.Thuocs = this;
		}
		
		private void detach_LoThuocs(LoThuocs entity)
		{
			this.SendPropertyChanging();
			entity.Thuocs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonThuoc")]
	public partial class DonThuocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonThuoc;
		
		private string _MaBacSi;
		
		private string _MaBenhNhan;
		
		private System.DateTime _NgayKe;
		
		private string _MoTaBenh;
		
		private EntitySet<CTDonThuocs> _CTDonThuocs;
		
		private EntitySet<HoaDons> _HoaDons;
		
		private EntityRef<BacSis> _BacSis;
		
		private EntityRef<BenhNhans> _BenhNhans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonThuocChanging(string value);
    partial void OnMaDonThuocChanged();
    partial void OnMaBacSiChanging(string value);
    partial void OnMaBacSiChanged();
    partial void OnMaBenhNhanChanging(string value);
    partial void OnMaBenhNhanChanged();
    partial void OnNgayKeChanging(System.DateTime value);
    partial void OnNgayKeChanged();
    partial void OnMoTaBenhChanging(string value);
    partial void OnMoTaBenhChanged();
    #endregion
		
		public DonThuocs()
		{
			this._CTDonThuocs = new EntitySet<CTDonThuocs>(new Action<CTDonThuocs>(this.attach_CTDonThuocs), new Action<CTDonThuocs>(this.detach_CTDonThuocs));
			this._HoaDons = new EntitySet<HoaDons>(new Action<HoaDons>(this.attach_HoaDons), new Action<HoaDons>(this.detach_HoaDons));
			this._BacSis = default(EntityRef<BacSis>);
			this._BenhNhans = default(EntityRef<BenhNhans>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonThuoc
		{
			get
			{
				return this._MaDonThuoc;
			}
			set
			{
				if ((this._MaDonThuoc != value))
				{
					this.OnMaDonThuocChanging(value);
					this.SendPropertyChanging();
					this._MaDonThuoc = value;
					this.SendPropertyChanged("MaDonThuoc");
					this.OnMaDonThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBacSi", DbType="VarChar(10)")]
		public string MaBacSi
		{
			get
			{
				return this._MaBacSi;
			}
			set
			{
				if ((this._MaBacSi != value))
				{
					if (this._BacSis.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBacSiChanging(value);
					this.SendPropertyChanging();
					this._MaBacSi = value;
					this.SendPropertyChanged("MaBacSi");
					this.OnMaBacSiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenhNhan", DbType="VarChar(10)")]
		public string MaBenhNhan
		{
			get
			{
				return this._MaBenhNhan;
			}
			set
			{
				if ((this._MaBenhNhan != value))
				{
					if (this._BenhNhans.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhNhanChanging(value);
					this.SendPropertyChanging();
					this._MaBenhNhan = value;
					this.SendPropertyChanged("MaBenhNhan");
					this.OnMaBenhNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKe", DbType="Date NOT NULL")]
		public System.DateTime NgayKe
		{
			get
			{
				return this._NgayKe;
			}
			set
			{
				if ((this._NgayKe != value))
				{
					this.OnNgayKeChanging(value);
					this.SendPropertyChanging();
					this._NgayKe = value;
					this.SendPropertyChanged("NgayKe");
					this.OnNgayKeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaBenh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MoTaBenh
		{
			get
			{
				return this._MoTaBenh;
			}
			set
			{
				if ((this._MoTaBenh != value))
				{
					this.OnMoTaBenhChanging(value);
					this.SendPropertyChanging();
					this._MoTaBenh = value;
					this.SendPropertyChanged("MoTaBenh");
					this.OnMoTaBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonThuocs_CTDonThuocs", Storage="_CTDonThuocs", ThisKey="MaDonThuoc", OtherKey="MaDonThuoc")]
		public EntitySet<CTDonThuocs> CTDonThuocs
		{
			get
			{
				return this._CTDonThuocs;
			}
			set
			{
				this._CTDonThuocs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonThuocs_HoaDons", Storage="_HoaDons", ThisKey="MaDonThuoc", OtherKey="MaDonThuoc")]
		public EntitySet<HoaDons> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BacSis_DonThuocs", Storage="_BacSis", ThisKey="MaBacSi", OtherKey="MaBacSi", IsForeignKey=true)]
		public BacSis BacSis
		{
			get
			{
				return this._BacSis.Entity;
			}
			set
			{
				BacSis previousValue = this._BacSis.Entity;
				if (((previousValue != value) 
							|| (this._BacSis.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BacSis.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._BacSis.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._MaBacSi = value.MaBacSi;
					}
					else
					{
						this._MaBacSi = default(string);
					}
					this.SendPropertyChanged("BacSis");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhans_DonThuocs", Storage="_BenhNhans", ThisKey="MaBenhNhan", OtherKey="MaBenhNhan", IsForeignKey=true)]
		public BenhNhans BenhNhans
		{
			get
			{
				return this._BenhNhans.Entity;
			}
			set
			{
				BenhNhans previousValue = this._BenhNhans.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhans.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhans.Entity = null;
						previousValue.DonThuocs.Remove(this);
					}
					this._BenhNhans.Entity = value;
					if ((value != null))
					{
						value.DonThuocs.Add(this);
						this._MaBenhNhan = value.MaBenhNhan;
					}
					else
					{
						this._MaBenhNhan = default(string);
					}
					this.SendPropertyChanged("BenhNhans");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTDonThuocs(CTDonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.DonThuocs = this;
		}
		
		private void detach_CTDonThuocs(CTDonThuocs entity)
		{
			this.SendPropertyChanging();
			entity.DonThuocs = null;
		}
		
		private void attach_HoaDons(HoaDons entity)
		{
			this.SendPropertyChanging();
			entity.DonThuocs = this;
		}
		
		private void detach_HoaDons(HoaDons entity)
		{
			this.SendPropertyChanging();
			entity.DonThuocs = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoThuoc")]
	public partial class LoThuocs : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoThuoc;
		
		private string _MaThuoc;
		
		private string _MaNCC;
		
		private string _DVT;
		
		private System.DateTime _NgayNhap;
		
		private System.DateTime _NgayHetHan;
		
		private int _SoLuong;
		
		private decimal _DonGia;
		
		private int _TrangThai;
		
		private EntitySet<CTHoaDons> _CTHoaDons;
		
		private EntityRef<NCCs> _NCCs;
		
		private EntityRef<Thuocs> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoThuocChanging(string value);
    partial void OnMaLoThuocChanged();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    partial void OnNgayHetHanChanging(System.DateTime value);
    partial void OnNgayHetHanChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(decimal value);
    partial void OnDonGiaChanged();
    partial void OnTrangThaiChanging(int value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public LoThuocs()
		{
			this._CTHoaDons = new EntitySet<CTHoaDons>(new Action<CTHoaDons>(this.attach_CTHoaDons), new Action<CTHoaDons>(this.detach_CTHoaDons));
			this._NCCs = default(EntityRef<NCCs>);
			this._Thuocs = default(EntityRef<Thuocs>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoThuoc
		{
			get
			{
				return this._MaLoThuoc;
			}
			set
			{
				if ((this._MaLoThuoc != value))
				{
					this.OnMaLoThuocChanging(value);
					this.SendPropertyChanging();
					this._MaLoThuoc = value;
					this.SendPropertyChanged("MaLoThuoc");
					this.OnMaLoThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10)")]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					if (this._Thuocs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="VarChar(10)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._NCCs.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date NOT NULL")]
		public System.DateTime NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this.OnNgayHetHanChanging(value);
					this.SendPropertyChanging();
					this._NgayHetHan = value;
					this.SendPropertyChanged("NgayHetHan");
					this.OnNgayHetHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Money NOT NULL")]
		public decimal DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoThuoc_CTHoaDons", Storage="_CTHoaDons", ThisKey="MaLoThuoc", OtherKey="MaLoThuoc")]
		public EntitySet<CTHoaDons> CTHoaDons
		{
			get
			{
				return this._CTHoaDons;
			}
			set
			{
				this._CTHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NCCs_LoThuoc", Storage="_NCCs", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public NCCs NCCs
		{
			get
			{
				return this._NCCs.Entity;
			}
			set
			{
				NCCs previousValue = this._NCCs.Entity;
				if (((previousValue != value) 
							|| (this._NCCs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NCCs.Entity = null;
						previousValue.LoThuocs.Remove(this);
					}
					this._NCCs.Entity = value;
					if ((value != null))
					{
						value.LoThuocs.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("NCCs");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuocs_LoThuoc", Storage="_Thuocs", ThisKey="MaThuoc", OtherKey="MaThuoc", IsForeignKey=true)]
		public Thuocs Thuocs
		{
			get
			{
				return this._Thuocs.Entity;
			}
			set
			{
				Thuocs previousValue = this._Thuocs.Entity;
				if (((previousValue != value) 
							|| (this._Thuocs.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuocs.Entity = null;
						previousValue.LoThuocs.Remove(this);
					}
					this._Thuocs.Entity = value;
					if ((value != null))
					{
						value.LoThuocs.Add(this);
						this._MaThuoc = value.MaThuoc;
					}
					else
					{
						this._MaThuoc = default(string);
					}
					this.SendPropertyChanged("Thuocs");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDons(CTHoaDons entity)
		{
			this.SendPropertyChanging();
			entity.LoThuocs = this;
		}
		
		private void detach_CTHoaDons(CTHoaDons entity)
		{
			this.SendPropertyChanging();
			entity.LoThuocs = null;
		}
	}
}
#pragma warning restore 1591
